Algoritmo "Concatenação"
// Descrição   : Aprendendo sobre concatenação
// Autor(a)    : Mateus Simões Neubarth
// Data atual  : 10/08/2020
Var
// Seção de Declarações das variáveis 
   nome: caractere
   numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite um nome: ")
   leia(nome)
   escreval("Digite um número inteiro: ")
   leia(numero)

   escreval(nome, ":", numero)

Fimalgoritmo