Algoritmo "Operadores Relacionais"
// Descrição   : Aprendendo sobre operadores relacionais
// Autor(a)    : Mateus Simões Neubarth
// Data atual  : 10/08/2020
Var
// Seção de Declarações das variáveis 
   nota01, nota02: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   nota01 := 10
   nota02 := 15
   
   se (nota01 <> nota02)entao
      escreval("Nota01 é diferente de Nota02")
   senao
      escreval("Nota01 é igual a Nota02")
   fimse

Fimalgoritmo