Algoritmo "Operadores aritiméticos"
// Descrição   : Aprendendo operadores aritiméticos
// Autor(a)    : Mateus Simões Neubarth
// Data atual  : 07/08/2020
Var
// Seção de Declarações das variáveis 
   resultado, valor01, valor02, valor03: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   valor01 := 10
   valor02 := 10
   valor03 := 10
   resultado := ((valor01 + valor02 + valor02) / valor03) % 2
   escreval("Resultado: ", resultado)

Fimalgoritmo